name: lteenb-lool
version: '2017-02-10'
summary: LTE Software eNodeB
description: |
  LTEENB is a LTE base station (eNodeB) implemented entirely in software
  and running on a PC. The PC generates a baseband signal which is sent
  to a radio front end doing the digital to analog conversion. The
  reverse is done for the reception.
grade: devel
confinement: devmode

apps:
  lteenb:
    command: lteenb-launcher
    daemon: simple
  systune:
    command: lte_init.sh
  set-license:
    command: set-license
  set-rfbackend:
    command: set-rfbackend

parts:
  # prebuilt LTEENB
  lteenb:
    plugin: dump
    source: lteenb-linux-2017-02-10.tar.gz
    # don't copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    # needed by lteenb binaries
    stage-packages: [ libsctp1, libuhd003, ]
    stage:
      # config but not driver selection machinery
      - -config/rf_driver
      - -config/rf_select.sh
      - config/*
      # original binaries and script
      - lib*.so
      - lteenb*
      - lte_init.sh
      - trx_*.so
      # from staged packages
      - lib/*/*.so.*
      - usr/lib/*/*.so.*
  # SoapySDR from source; build-dep of LimeSuite; not needed after build as we
  # don't ship the SoapySDR LMS modules
  soapysdr:
    plugin: cmake
    source: https://github.com/pothosware/SoapySDR.git
    build-packages: [ gcc, g++ ]
    prime:
      # don't copy anything in the final snap
      - -*
  # LimeSuite from source; only need the libLimeSuite part
  liblimesuite:
    after: [ soapysdr, ]
    plugin: cmake
    source: https://github.com/myriadrf/LimeSuite.git
    build-packages: [ libsqlite3-dev, libusb-1.0-0-dev ]
    stage-packages: [ libsqlite3-0, libusb-1.0-0 ]
    prime:
      # only copy the shared library and libs from staged packages to the final
      # snap; not headers or SoapySDR module
      - lib/libLimeSuite.so.*
      - lib/*/*.so.*
      - usr/lib/*/*.so.*
  # libLimeSuite from debs; if you prefer using the prebuilt APT packages
  # instead of building from source, add the myriadrf/drivers PPA, comment out
  # the soapysdr and liblimesuite parts above and uncomment this one
#  liblimesuite:
#    plugin: nil
#    build-packages: [ liblimesuite-dev, ]
#    stage-packages: [ liblimesuite17.01-1, ]
#    stage:
#      - lib/*/*.so.*
#      - usr/lib/*/*.so.*
  # LimeSDR TRX backend
  trx-lms:
    plugin: make
    source: https://github.com/lool/trx-lms7002m.git
    after: [ liblimesuite, ]
    # don't automatically copy missing shared libs
    build-attributes: [ no-system-libraries, ]
    # workaround missing CPPFLAGS and LDFLAGS in Makefile
    install: |
      cp -f trx_*.so $SNAPCRAFT_PART_INSTALL
      mkdir -p $SNAPCRAFT_PART_INSTALL/config
      rm -rf $SNAPCRAFT_PART_INSTALL/config/limeSDR
      cp -rf config-limeSDR $SNAPCRAFT_PART_INSTALL/config/limeSDR
    stage:
      - config/*
      - lib/*/*.so.*
      - trx_*.so
      - usr/lib/*/*.so.*
  # snap integration bits
  glue:
    plugin: dump
    source: glue
    install: |
      # ship static symlink pointing to writable dir
      mkdir -p $SNAPCRAFT_PART_INSTALL/config
      ln -nsf /var/snap/lteenb-lool/current/rf_driver \
          $SNAPCRAFT_PART_INSTALL/config/rf_driver

